### ISSUE TITLE
ClassNotFoundException "JsonConfig$KeyStrategy"

### ISSUE THREAD

**Issue by baztian** [eclipse-ee4j/parsson#72]
For the following code I'm getting

    Exception in thread "main" java.lang.NoClassDefFoundError: jakarta/json/JsonConfig$KeyStrategy
        at org.eclipse.parsson.JsonObjectBuilderImpl$DuplicateStrategy.<clinit>(JsonObjectBuilderImpl.java:373)
        at org.eclipse.parsson.JsonObjectBuilderImpl.<init>(JsonObjectBuilderImpl.java:59)
        at org.eclipse.parsson.JsonObjectBuilderImpl.<init>(JsonObjectBuilderImpl.java:54)
        at org.eclipse.parsson.JsonProviderImpl.createObjectBuilder(JsonProviderImpl.java:178)
        at jakarta.json.Json.createObjectBuilder(Json.java:275)
        at Scratch.main(scratch_4.java:8)
    Caused by: java.lang.ClassNotFoundException: jakarta.json.JsonConfig$KeyStrategy
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        ... 6 more

This only happens once I increase parsson dependency from 1.0.0 to 1.1.1.

    import static jakarta.json.Json.createObjectBuilder;
    
    import jakarta.json.JsonObject;
    
    class Scratch {
    
      public static void main(String[] args) {
        JsonObject deliveryEvent = createObjectBuilder()
            .add("mail", createObjectBuilder()
                .add("timestamp", "2021-07-09T09:02:45.234386+00:00")
                .add("messageId", "3191054b-ef87-4959-81af-9e851088a507")
                .build()
            ).build();
      }
    }

**Comment by jbescos** [comment]
I am running your example and it works well with this dependency:
```
		<dependency>
			<groupId>org.eclipse.parsson</groupId>
			<artifactId>parsson</artifactId>
			<version>1.1.1</version>
		</dependency>
```
It seems you have a wrong jakarta.json:jakarta.json-api dependency version in the classpath or modulepath.

In case you are using maven, you can run this to check what is that version:
`mvn dependency:tree`

```
[INFO] \- org.eclipse.parsson:parsson:jar:1.1.1:compile
[INFO]    \- jakarta.json:jakarta.json-api:jar:2.1.1:compile
```

**Comment by jbescos** [comment]
Closing
